version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develope
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
