version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Tokyo
    groups:
      actions-cache:
        patterns:
          - "actions/cache*"
    open-pull-requests-limit: 5
  - package-ecosystem: uv
    directory: /
    target-branch: develop
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Tokyo
    groups:
      routine-updates:
        patterns:
          - "*"
        exclude-patterns:
          - ruff
        update-types:
          - patch
          - minor
    open-pull-requests-limit: 5
