"""Public stateless use case job entry points."""

from werewolf_agent.domain.llm.models import FakeLlmConfig, FakeLlmStrategy
from werewolf_agent.usecase.jobs._agents import FakeLlmAgentFactory
from werewolf_agent.usecase.jobs.games import (
    AdvanceGameCommand,
    AdvanceGameResult,
    CreateGameCommand,
    GameEventCreate,
    GameNotFoundError,
    GamePhase,
    GameResult,
    GameRunCreate,
    GameRunsResult,
    GameRunUpdate,
    GameStatus,
    GameTurnsResult,
    GameUseCaseConfig,
    GameUseCaseDependencies,
    GetGameQuery,
    InvalidGameIdError,
    ListGamesQuery,
    ListGameTurnsQuery,
    ListPublicEventsQuery,
    PublicEventsResult,
    PublicGameRunSummary,
    PublicGameTurn,
    RulesetResult,
    StoredGameEvent,
    StoredGameRun,
    StoredGameRunSummary,
    StoredGameTurn,
    advance_game,
    create_game,
    get_default_ruleset,
    get_game,
    list_game_turns,
    list_games,
    list_public_events,
)
from werewolf_agent.usecase.jobs.ports import AgentFactory, GameRepository, PlayerAgent

__all__ = [
    "AdvanceGameCommand",
    "AdvanceGameResult",
    "AgentFactory",
    "CreateGameCommand",
    "FakeLlmAgentFactory",
    "FakeLlmConfig",
    "FakeLlmStrategy",
    "GameEventCreate",
    "GameNotFoundError",
    "GamePhase",
    "GameRepository",
    "GameResult",
    "GameRunCreate",
    "GameRunUpdate",
    "GameRunsResult",
    "GameStatus",
    "GameTurnsResult",
    "GameUseCaseConfig",
    "GameUseCaseDependencies",
    "GetGameQuery",
    "InvalidGameIdError",
    "ListGameTurnsQuery",
    "ListGamesQuery",
    "ListPublicEventsQuery",
    "PlayerAgent",
    "PublicEventsResult",
    "PublicGameRunSummary",
    "PublicGameTurn",
    "RulesetResult",
    "StoredGameEvent",
    "StoredGameRun",
    "StoredGameRunSummary",
    "StoredGameTurn",
    "advance_game",
    "create_game",
    "get_default_ruleset",
    "get_game",
    "list_game_turns",
    "list_games",
    "list_public_events",
]
