"""公開Python application facade."""

from werewolf_agent.application.constants import DeliberationLevel
from werewolf_agent.application.errors import (
    AppError,
    ConfigError,
    ErrorCode,
    GameError,
    GamePhaseError,
    ResourceNotFoundError,
)
from werewolf_agent.application.facade import Actor, GameApplication
from werewolf_agent.application.models import (
    AdvanceGameResult,
    ApplicationContext,
    ComputedAdvanceGame,
    CreateGameCommand,
    GameApplicationConfig,
    GameEventCreate,
    GameListResult,
    GameRecordCreate,
    GameRecordUpdate,
    GameResult,
    GameRevealAction,
    GameRevealInspection,
    GameRevealNight,
    GameRevealPlayer,
    GameRevealResult,
    GameRevealVote,
    GameSetupOptionsResult,
    GameTimelineResult,
    GeneratedPlayerInput,
    PlayerActionCommand,
    PlayerActionResult,
    PlayerObservationResult,
    PlayerPreviewResult,
    PreparedAdvanceGame,
    ReplayVerificationResult,
    SetupValidationResult,
    StoredGame,
    StoredGameEvent,
    StoredGameSummary,
    StoredGameTurn,
)
from werewolf_agent.application.operations import AccessPolicy, OperationQueue, QueuedOperation
from werewolf_agent.application.ports import GameRepository, SetupRepository
from werewolf_agent.application.setup_catalog import SetupTemplateCatalog, SetupTemplateMetadata
from werewolf_agent.application.setup_document import (
    AbilityDefinition,
    AttackAbility,
    DeathReactionAbility,
    EliminateAbility,
    GameSetupDocument,
    ImmunityAbility,
    InspectAbility,
    KnowledgeAbility,
    LocalRulesDefinition,
    MechanicsDefinition,
    PlayerGenerationDefinition,
    PlayerIdentityDefinition,
    PrivateStrategyDefinition,
    ProtectAbility,
    PublicPersonaDefinition,
    RoleDefinition,
    ThemeDefinition,
    VulnerabilityAbility,
)
from werewolf_agent.application.setup_facade import SetupApplication
from werewolf_agent.application.setup_options import validate_setup_document
from werewolf_agent.application.setup_records import SavedSetupRevision, SavedSetupSummary
from werewolf_agent.application.types import GameStatus

__all__ = [
    "AbilityDefinition",
    "AccessPolicy",
    "Actor",
    "AdvanceGameResult",
    "AppError",
    "ApplicationContext",
    "AttackAbility",
    "ComputedAdvanceGame",
    "ConfigError",
    "CreateGameCommand",
    "DeathReactionAbility",
    "DeliberationLevel",
    "EliminateAbility",
    "ErrorCode",
    "GameApplication",
    "GameApplicationConfig",
    "GameError",
    "GameEventCreate",
    "GameListResult",
    "GamePhaseError",
    "GameRecordCreate",
    "GameRecordUpdate",
    "GameRepository",
    "GameResult",
    "GameRevealAction",
    "GameRevealInspection",
    "GameRevealNight",
    "GameRevealPlayer",
    "GameRevealResult",
    "GameRevealVote",
    "GameSetupDocument",
    "GameSetupOptionsResult",
    "GameStatus",
    "GameTimelineResult",
    "GeneratedPlayerInput",
    "ImmunityAbility",
    "InspectAbility",
    "KnowledgeAbility",
    "LocalRulesDefinition",
    "MechanicsDefinition",
    "OperationQueue",
    "PlayerActionCommand",
    "PlayerActionResult",
    "PlayerGenerationDefinition",
    "PlayerIdentityDefinition",
    "PlayerObservationResult",
    "PlayerPreviewResult",
    "PreparedAdvanceGame",
    "PrivateStrategyDefinition",
    "ProtectAbility",
    "PublicPersonaDefinition",
    "QueuedOperation",
    "ReplayVerificationResult",
    "ResourceNotFoundError",
    "RoleDefinition",
    "SavedSetupRevision",
    "SavedSetupSummary",
    "SetupApplication",
    "SetupRepository",
    "SetupTemplateCatalog",
    "SetupTemplateMetadata",
    "SetupValidationResult",
    "StoredGame",
    "StoredGameEvent",
    "StoredGameSummary",
    "StoredGameTurn",
    "ThemeDefinition",
    "VulnerabilityAbility",
    "validate_setup_document",
]
