"""公開Python application facade."""

from werewolf_agent.application.actor import Actor
from werewolf_agent.application.constants import DeliberationLevel
from werewolf_agent.application.embedding import (
    EmbeddedApplication,
    InlineCommandExecutor,
    SingleTenantAccessPolicy,
    create_embedded_application,
)
from werewolf_agent.application.errors import (
    AppError,
    ConfigError,
    ErrorCode,
    GameError,
    GamePhaseError,
    InternalError,
    ResourceNotFoundError,
)
from werewolf_agent.application.facade import GameApplication
from werewolf_agent.application.memory import Clock, InMemoryGameRepository, InMemorySetupRepository
from werewolf_agent.application.models import (
    AdvanceGameCommand,
    AdvanceGameResult,
    ApplicationContext,
    ComputedAdvanceGame,
    CreateGameCommand,
    GameApplicationConfig,
    GameEventCreate,
    GameListResult,
    GameRecordCreate,
    GameRecordUpdate,
    GameResult,
    GameRevealAction,
    GameRevealInspection,
    GameRevealNight,
    GameRevealPlayer,
    GameRevealResult,
    GameRevealVote,
    GameSetupOptionsResult,
    GameTimelineResult,
    GeneratedPlayerInput,
    PlayerActionCommand,
    PlayerActionResult,
    PlayerObservationResult,
    PlayerPreviewResult,
    PreparedAdvanceGame,
    ReplayVerificationResult,
    SetupValidationResult,
    StoredGame,
    StoredGameEvent,
    StoredGameSummary,
    StoredGameTurn,
)
from werewolf_agent.application.operations import AccessPolicy, OperationQueue, QueuedOperation
from werewolf_agent.application.ports import GameRepository, SetupRepository, Transaction
from werewolf_agent.application.rule_packs import (
    RulePackRegistry,
    create_core_rule_policy_registry,
)
from werewolf_agent.application.setup_catalog import SetupTemplateCatalog, SetupTemplateMetadata
from werewolf_agent.application.setup_facade import SetupApplication
from werewolf_agent.application.setup_options import parse_setup_document, validate_setup_document
from werewolf_agent.application.setup_records import SavedSetupRevision, SavedSetupSummary
from werewolf_agent.application.types import GameStatus

__all__ = [
    "AccessPolicy",
    "Actor",
    "AdvanceGameCommand",
    "AdvanceGameResult",
    "AppError",
    "ApplicationContext",
    "Clock",
    "ComputedAdvanceGame",
    "ConfigError",
    "CreateGameCommand",
    "DeliberationLevel",
    "EmbeddedApplication",
    "ErrorCode",
    "GameApplication",
    "GameApplicationConfig",
    "GameError",
    "GameEventCreate",
    "GameListResult",
    "GamePhaseError",
    "GameRecordCreate",
    "GameRecordUpdate",
    "GameRepository",
    "GameResult",
    "GameRevealAction",
    "GameRevealInspection",
    "GameRevealNight",
    "GameRevealPlayer",
    "GameRevealResult",
    "GameRevealVote",
    "GameSetupOptionsResult",
    "GameStatus",
    "GameTimelineResult",
    "GeneratedPlayerInput",
    "InMemoryGameRepository",
    "InMemorySetupRepository",
    "InlineCommandExecutor",
    "InternalError",
    "OperationQueue",
    "PlayerActionCommand",
    "PlayerActionResult",
    "PlayerObservationResult",
    "PlayerPreviewResult",
    "PreparedAdvanceGame",
    "QueuedOperation",
    "ReplayVerificationResult",
    "ResourceNotFoundError",
    "RulePackRegistry",
    "SavedSetupRevision",
    "SavedSetupSummary",
    "SetupApplication",
    "SetupRepository",
    "SetupTemplateCatalog",
    "SetupTemplateMetadata",
    "SetupValidationResult",
    "SingleTenantAccessPolicy",
    "StoredGame",
    "StoredGameEvent",
    "StoredGameSummary",
    "StoredGameTurn",
    "Transaction",
    "create_core_rule_policy_registry",
    "create_embedded_application",
    "parse_setup_document",
    "validate_setup_document",
]
