"""Compatibility re-exports for games API DTOs."""

from werewolf_agent.interfaces.api.schemas import (
    CreateGameAgentConfig,
    CreateGamePlayer,
    CreateGameRequest,
    CreateGameRuleConfig,
    GameEventsQuery,
    GameEventsResponse,
    GamePhase,
    GameResponse,
    GameStatus,
    PublicGameEvent,
    PublicGameState,
    PublicPlayerState,
    RoleId,
    RulesetResponse,
    StepGameResponse,
    TieBreakPolicyId,
    Winner,
)

__all__ = [
    "CreateGameAgentConfig",
    "CreateGamePlayer",
    "CreateGameRequest",
    "CreateGameRuleConfig",
    "GameEventsQuery",
    "GameEventsResponse",
    "GamePhase",
    "GameResponse",
    "GameStatus",
    "PublicGameEvent",
    "PublicGameState",
    "PublicPlayerState",
    "RoleId",
    "RulesetResponse",
    "StepGameResponse",
    "TieBreakPolicyId",
    "Winner",
]
