@echo off
setlocal

set "FAILED=0"
set "STATUS_ENV=%TEMP%\werewolf-agent\supabase-status.env"
set "SUPABASE_TELEMETRY_DISABLED=1"

if /I "%~1"=="--help" goto print_help
if /I "%~1"=="-h" goto print_help
if not "%~1"=="" (
    echo Unknown option: %~1 1>&2
    echo Run scripts\preflight-supabase.cmd --help for usage. 1>&2
    exit /b 2
)

pushd "%~dp0" || exit /b 1
if not exist "pyproject.toml" (
    if exist "..\pyproject.toml" (
        cd ..
    ) else (
        echo Could not find repository root. 1>&2
        popd
        exit /b 1
    )
)

set "PYTHON=%CD%\.venv\Scripts\python.exe"
if not exist "%PYTHON%" (
    echo Missing virtual environment: %PYTHON% 1>&2
    echo Run: uv sync --group dev --group docs --extra streamlit --extra worker --link-mode=copy 1>&2
    popd
    exit /b 1
)

if defined PYTHONPATH (
    set "PYTHONPATH=%CD%\src;%PYTHONPATH%"
) else (
    set "PYTHONPATH=%CD%\src"
)
if not defined WEREWOLF_LOG_FILE_NAME (
    set "WEREWOLF_LOG_FILE_NAME=cli.jsonl"
)

echo Checking Docker engine...
docker version >nul 2>&1
if errorlevel 1 (
    echo Docker engine is not available. Start Docker Desktop before launching Streamlit. 1>&2
    popd
    exit /b 1
)

echo Checking Supabase local stack...
supabase status -o env >nul 2>&1
if errorlevel 1 (
    echo Supabase local stack is not running. Starting Supabase...
    supabase start
    if errorlevel 1 (
        popd
        exit /b 1
    )
)

call :write_env_from_supabase_status
call :require_env_line WEREWOLF_SUPABASE_URL
call :require_env_line WEREWOLF_SUPABASE_PUBLISHABLE_KEY
call :require_env_line WEREWOLF_SUPABASE_DB_DSN
if "%FAILED%"=="1" (
    popd
    exit /b 1
)

echo Applying Supabase migrations...
supabase migration up >nul
if errorlevel 1 (
    popd
    exit /b 1
)

echo Checking werewolf-agent doctor...
"%PYTHON%" -m werewolf_agent doctor --output json >nul
if errorlevel 1 (
    popd
    exit /b 1
)

echo Checking Supabase setup options...
"%PYTHON%" -m werewolf_agent setup-options >nul
if errorlevel 1 (
    popd
    exit /b 1
)

echo Supabase preflight passed.
popd
exit /b 0

:write_env_from_supabase_status
if not exist "%TEMP%\werewolf-agent" (
    mkdir "%TEMP%\werewolf-agent" >nul 2>nul
)
supabase status -o env > "%STATUS_ENV%"
if errorlevel 1 exit /b 1

for /f "usebackq tokens=1,* delims==" %%A in ("%STATUS_ENV%") do (
    if /I "%%A"=="API_URL" set "STATUS_SUPABASE_URL=%%~B"
    if /I "%%A"=="PUBLISHABLE_KEY" set "STATUS_SUPABASE_PUBLISHABLE_KEY=%%~B"
    if /I "%%A"=="DB_URL" set "STATUS_SUPABASE_DB_URL=%%~B"
)

if not defined STATUS_SUPABASE_URL (
    echo supabase status -o env did not provide API_URL. 1>&2
    exit /b 1
)
if not defined STATUS_SUPABASE_PUBLISHABLE_KEY (
    echo supabase status -o env did not provide PUBLISHABLE_KEY. 1>&2
    exit /b 1
)
if not defined STATUS_SUPABASE_DB_URL (
    echo supabase status -o env did not provide DB_URL. 1>&2
    exit /b 1
)

if not exist ".env" (
    > ".env" echo # Generated by scripts\preflight-supabase.cmd from supabase status -o env.
)
call :ensure_env_value WEREWOLF_SUPABASE_URL "%STATUS_SUPABASE_URL%"
call :ensure_env_value WEREWOLF_SUPABASE_PUBLISHABLE_KEY "%STATUS_SUPABASE_PUBLISHABLE_KEY%"
call :ensure_env_value VITE_SUPABASE_URL "%STATUS_SUPABASE_URL%"
call :ensure_env_value VITE_SUPABASE_PUBLISHABLE_KEY "%STATUS_SUPABASE_PUBLISHABLE_KEY%"
call :ensure_env_value WEREWOLF_SUPABASE_DB_DSN "%STATUS_SUPABASE_DB_URL%"
exit /b 0

:ensure_env_value
findstr /R /C:"^%~1=." ".env" >nul
if errorlevel 1 (
    >> ".env" echo %~1=%~2
)
exit /b 0

:require_env_line
findstr /R /C:"^%~1=." ".env" >nul
if errorlevel 1 (
    echo Missing required .env key: %~1 1>&2
    set "FAILED=1"
)
exit /b 0

:print_help
echo Usage: scripts\preflight-supabase.cmd
echo.
echo Verifies the Supabase-only local runtime before launching Streamlit.
echo Starts the local Supabase stack when needed and creates .env from
echo supabase status -o env when required.
echo Required .env keys:
echo   WEREWOLF_SUPABASE_URL
echo   WEREWOLF_SUPABASE_PUBLISHABLE_KEY
echo   WEREWOLF_SUPABASE_DB_DSN
echo.
echo Also checks Docker, migrations, doctor, and setup-options.
exit /b 0
