[local_rules]
allow_self_vote = false
allow_vote_revision = false
allow_night_action_revision = false
enable_first_night_attack = true
enable_no_elimination_on_tie = true
enable_random_elimination_on_tie = false
allow_knight_self_guard = true
allow_knight_repeat_guard = true
allow_seer_self_inspect = false
allow_werewolf_friendly_fire = false
reveal_role_on_death = false
